### ISSUE TITLE
skip events / event seeking

### ISSUE THREAD

**Issue by dneise** [cta-observatory/pyeventio#127]
@watsonjj mentioned event seeking on slack

https://ctapipe.slack.com/archives/GET7W217C/p1544720179022400

We assume this might not really be needed ... So decided to not implement this.
Any other opinions?

**Comment by kosack** [comment]
It's only useful in special cases (like guis, etc).  Nevertheless, it would probably be quite easy to add a function that loops through all events without parsing everything other than the start of the event, returning a dict of event_number (or event_id) mapped to offset in file. Then a separate function say `seek(position)` would provide the functionality to go to the given file position (internally just a fseek), and the usual parsing would continue as if they were at the start of the file.  So the user would do something like:

```py3
event_index = events.build_index() 
events.seek(event_index[367])
event_367 = next(events)
```

or store the index internally, so the user just does `events.seek(367)` (which fails if build_index has not been run)

**Comment by dneise** [comment]
I think if we support direct event access, we should support a simple interface like `__getitem__`. 
But then the immediate question arises, what kind of numeric index dies getitem expect? A running counter? or the event_id? 
Another approach could be something like:
```python

with SimTelFile(path) as file:
    specific_event = file.event_by_id(some_id_I_happen_to_know_by_heart)
    specific_shower = file.shower_by_id(a_shower_id_I_know_by_heart)
    # showers can again be iterated and just return all the "re-use" events.
    for event in specific_shower:
        pass
    # or one can select a specific event from a shower as well:
    specific_event_2 = specific_shower.event_by_id(some_id)
```
However, there is no way foreseen, to get a list of all `event_id`s in a file other than iterating over it, but iterating takes time...

This `event_by_id` and `shower_by_id` interface is uncommon an needs to be documented well. People will still often overlook it and use iteration to find what they need. 

Also files exist, containing multiple runs. To my knowledge an event_id is only guaranteed to be unique within a run. So I have no idea how to implement `event_by_id` for a file consisting of multiple runs.

**Comment by dneise** [comment]
So I honestly wonder if adding possibly obscure features, hardly ever needed, is worth our time at the moment

**Comment by MaxNoe** [comment]
EventIOFiles, due to the way we read them (appending to lists, updating objects for the last seen object of a type) basically forbid random access or skipping over large parts of the file.

Implementing this properly, will be very complex and not supported for the fast zstd compression.

Thus, I think we can make the decision not to implement a random access layer in this library.
