### ISSUE TITLE
conda packages

### ISSUE THREAD

**Issue by kosack** [cta-observatory/pyeventio#134]
Would it be possible to maintain a conda package of this?  Since ctapipe uses conda for the recommended install, it would be very useful to have the ctapipe conda package depend on this package without using a pip hack.  That will be needed for the next release. TI's quite easy to create a recipe using `conda skeleton pypi eventio`.  Then we either:

1) host the recipe on the cta-conda-recipes repo and manually build it ourselves when there is a new relase

2) put it on conda-forge for automatic building (recommended)

**Comment by dneise** [comment]
I must admit I tried to understand how to make conda packages once and failed. Do you know a good resource to learn about this? 

I think Max knows how it works. Maybe he can do it right away.

Question: What is a pip hack?

**Comment by MaxNoe** [comment]
I think @kosack referred to mixing conda and pip packages in `environment.yml` files.

**Comment by kosack** [comment]
I've already make packages for it, the package recipe is for now in the https://github.com/cta-observatory/cta-conda-recipes repo.  Eventually we should automate the builds of the packages, though, or move it to conda-forge so it's done automatically by them.

**Comment by kosack** [comment]
you can see the recipe here: https://github.com/cta-observatory/cta-conda-recipes/blob/master/eventio/meta.yaml
