### ISSUE TITLE
Writing simtelarray files?

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/pyeventio#141]
Are there any plans to make pyeventio able to write files? It would be very useful to have reduced versions of the MC files (removing pixels which have small signals, i.e. a R0=>DL0 reduction), so that we do not need to go through the full raw files to re-calculate IRFs - except to test new pixel selection algorithms. That can of course be done now from DL1 HDF5 files, but that is already after pulse integration and cleaning; having DL0 files of manageable size would allow to test changes in pulse integration and cleaning much more easily.  An alternative would be to have DL0 MC files in some other format, but I am not aware this exists yet.

**Comment by MaxNoe** [comment]
At first, when we first started, we thought this would be crazy.

Last week, we thought about *filterting out* objects, which would be dramatically easier than writing arbitrary objects.

This would also be handy for generating test data for this project and ctapipe.

Would this be enough for you? E.g. filtering out all containers, that don't belong to a certain telescope type?

**Comment by moralejo** [comment]
> 
> Would this be enough for you? E.g. filtering out all containers, that don't belong to a certain telescope type?

That would have some applications indeed, but I was thinking of keeping only significant pixels in each camera event, i.e. a zero suppression.  Simtelarray allows that (keeping different lists of pixels for each event), but the default execution mode I think it is all pixels written (for triggered events & cameras). So it would not be as simple as just filtering out data blocks.
I guess that leaving the structure unchanged, and simply set to 0 all traces of non-significant pixels, should improve the compression factor, but perhaps not make things much faster in terms of processing them through ctapipe.

So we are left with two possibilities if we want to have DL0-like samples for fast testing of the full ctapipe chain until IRF production:
- to do the R0->DL0 zero suppression directly in simtelarray
- to do it with ctapipe, but write the DL0 output in a different format  

Opinions?

**Comment by vuillaut** [comment]
Hi.

My opinion on that:
- I would not go into the effort (unless I am mistaken and it is easy to do...) to be able to write simtel_array files.
- The issue is taking much more time than we all would like to, but a DL0 data format should be decided at some point. It would be much more useful to write MC data in this format and develop the tools to read/write this format and then do all the tests we need.
- If it really cannot wait, I would suggest extending the effort of writing data into HDF5 format. It's been my hope from the beginning to extend the DL1 data handler to a "DL0 data handler" at some point as we'll be doing machine learning directly on DL0 data in the future.

My apologies but making important developments to handling simtel_array format feels to me like moving backward when we desperately need to move forward...

**Comment by MaxNoe** [comment]
>     * I would not go into the effort (unless I am mistaken and it is easy to do...) to be able to write simtel_array files.

It's certainly not easy. It will be a lot of work, to get something that works which produces identical files to simtelarray.

**Comment by MaxNoe** [comment]
>     * The issue is taking much more time than we all would like to, but a DL0 data format should be decided at some point. It would be much more useful to write MC data in this format and develop the tools to read/write this format and then do all the tests we need.

I fully and wholeheartedly agree

**Comment by moralejo** [comment]
Thanks for the feedback. There is indeed no need to write the files in simtelarray format. The use of an HDF5 DL0 format would be perfectly fine for me. Waiting for the official definition of DL0 could be considered if there was a clear date for that, but there is none. I also understand that working in a DL0 format that will become deprecated is not very appealing. I will try to find out what level of (safe) reduction can be achieved with the zero-suppression options of simtelarray, so that we directly produce the files with insignificant pixels already removed - then there is the question whether pyeventio can _read_ that kind of simtelarray files.

**Comment by MaxNoe** [comment]
> Waiting for the official definition of DL0 could be considered if there was a clear date for that, but there is none.

Maybe that's just my impression, but: I think what ever will be first presented as a viable DL0 format will become *the* DL0 format, after a very brief discussion and possible iteration over found issues.

Nobody but us, the people writing analysis code, will produce a DL0 spec.
So actually starting to work on *a* DL0 format will probably lead to *the* DL0 format.

If I'm mistaken, and there are some real efforts ongoing on writing the specs, I'm sorry but it seems this was the case for most part of the cta developements until now.

**Comment by vuillaut** [comment]
Actually there are on-going efforts to both 
- write the specs (mostly by @kosack)
- testing the DL0 candidates

**Comment by moralejo** [comment]
Ok, I think we can close this issue, writing simtelarray files from ctapipe with pixel selection seems too complicated. It seems we can perform the pixel selection using the read_cta program of libhessio, and create in this way the "zero-suppressed" simtel files outside ctapipe.
