### ISSUE TITLE
Read calibration events (2028)

### ISSUE THREAD

**Issue by kpfrang** [cta-observatory/pyeventio#151]
Hi all,
currently, I'm working on implementing the time-next-neighbor cleaning described [here](https://arxiv.org/pdf/1307.4939.pdf) in ctapipe. 
For this I need to read calibration events (block 2028). Currently I'm still doing this with `pyhessio`. However, it would be nice to have it all in `pyeventio` and if would be possible to select which event type is read I guess.

A small file with calibration events be found in this [link](https://desycloud.desy.de/index.php/s/44HjgGRtpDGyAzF).

**Comment by MaxNoe** [comment]
Ok, nice.

Turns out, CalibEvents is just a container for a regular array event, so nothing new has to be emplemented.

I will just also yield calibration events in the simtelfile

**Comment by MaxNoe** [comment]
See #152
