### ISSUE TITLE
EventIOFile and EventIOObject reset on `__iter__`

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/pyeventio#173]
This is not good for some optimizations I wanted to try and generally not expected.

Current behaviour:

```
f = EventIOFile('...')

o = next(f)

for o in f:
    # tries to start over, backwards seeking and stuff
```

**Comment by vuillaut** [comment]
Hi @MaxNoe and @dneise 
Has this issue been solved?
With the last version of eventio and ctapipe master, when I do 
```
event = next(iter(source))
for event in source:
```
I basically get this backward seeking error again:
`raise IOError('Only forward seeking possible')`

Should I do things differently?
The error seems to come from eventio but could be ctapipe...

**Comment by MaxNoe** [comment]
> Should I do things differently?

`ctapipe.io.EventSource` is a generator, not an iterator. So calling `__iter__` again, will try to start over.

You could do

```python
event_iterator = iter(source)
event = next(event_iterator)
for event in event_iterator:
    ...
```

Then, `__iter__` is only called once.

This is not an eventio issue I think, but ctapipe one.
I would opt for the ctapipe event source to be an iterator, not a generator.

**Comment by vuillaut** [comment]
Thank for the swift reply @MaxNoe and for the suggestion.
