### ISSUE TITLE
Error during installation after conda update

### ISSUE THREAD

**Issue by Hckjs** [cta-observatory/pyeventio#185]
Hey,
I'm just trying to install eventio on two different devices (Ubuntu and Arch-Linux with Python=3.7). First time it works with Ubuntu with an older Conda-Version (don't know the exact version, but roughly 6 months without update). After I updated conda i got some Errors:

First i was trying to create the ctapipe env including eventio (git clone ctapipe and [this](https://github.com/cta-observatory/ctapipe/blob/master/environment.yml) .yml) and got this Error:

[env_yml_eventio_error.txt](https://github.com/cta-observatory/pyeventio/files/3501459/env_yml_eventio_error.txt)

pytest got me this:

[pytest_error.txt](https://github.com/cta-observatory/pyeventio/files/3501462/pytest_error.txt)

and after trying to install eventio separately with pip install eventio i got this Error:

[separate_eventio_error.txt](https://github.com/cta-observatory/pyeventio/files/3501369/seperat_eventio_error.txt)

regards
Jonas

**Comment by MaxNoe** [comment]
Hi,

This looks like an outdated `wheel` version.

Can you do

```
$ conda list wheel
$ pip freeze | grep wheel
```

And report what it says?

You might want to try `conda update wheel`

**Comment by MaxNoe** [comment]
Found here: This seems to be a python 3.7.4 issue, maybe try downgrading to 3.7.3?

**Comment by MaxNoe** [comment]
Also see here: https://github.com/ContinuumIO/anaconda-issues/issues/11195

**Comment by MaxNoe** [comment]
Ok, so the issue should be fixed, instead of downgrading, it should be possible to just

`conda update python`, which will install a new build of python 3.7.4 that does not have this problem.

Closing here, as this is an anaconda issue.
