### ISSUE TITLE
Problem with PixelSettings version 

### ISSUE THREAD

**Issue by FrancaCassol** [cta-observatory/pyeventio#191]
Hi,

I would like to read simtel files produced with the last MC version (corsika7.6_simtelarray). 
I already updated eventio to the last version in order not to have problems with the  type 1216 (thanks @MaxNoe ;-) ), but still I have a problem with the pixel setting version : 

```
/scratch4/CTA_soft/anaconda3/envs/cta-dev/lib/python3.6/site-packages/eventio/version_handling.py in assert_max_version(self, last_supported)
     39                 name=self.__class__.__name__,
     40                 last_supported=last_supported,
---> 41                 given_version=self.header.version,
     42             )
     43         )

NotImplementedError: Unsupported version of PixelSettings: only versions up 
to 2 supported, got: 3 
```
I am reading file produced by the LightEmission package. 
Thanks for any help

**Comment by MaxNoe** [comment]
Will check simtel for the new version. Maybe tomorrow.

**Comment by MaxNoe** [comment]
Can you provide a smallish file? Few telescopes and showers?

You can check by using `eventio_print_object_informatoin` if the file contains PixelSettings with version 3.

**Comment by FrancaCassol** [comment]
> Can you provide a smallish file? Few telescopes and showers?

You find it in https://www.cppm.in2p3.fr/~cassol/LST/

> You can check by using `eventio_print_object_informatoin` if the file contains PixelSettings with version 3.

How can I run it from a jupyter notebook?

**Comment by MaxNoe** [comment]
It's a commandline Tool.

So `eventio_print_object_information <inputfile>`

**Comment by MaxNoe** [comment]
@FrancaCassol new release 0.21.4 is out with support for the new PixelSettings version and two other new containers that were in the file you provided.
