### ISSUE TITLE
photon_count seems to be cumulative

### ISSUE THREAD

**Issue by thomasarmstrong** [cta-observatory/pyeventio#208]
I have noticed when I loop through events, photon_counts retains the previous photon count in the array and adds the new values?

e.g. 

```python
f = SimTelFile('run3.simtel.gz') 
for event in f: 
    print(sum(event['photoelectrons'][0]['photon_counts'])) 
                                                                                                                                                                                                    
109
136
276
348
735
810
1195
1533
1696
1894
1952
2320
...
```

**Comment by MaxNoe** [comment]
We currently don't have a test file with photon counts present.

Which simtel options are necessary so this is filled?

**Comment by MaxNoe** [comment]
Oh, it seems to be a compile time options, `-DSTORE_PIX_PHOTONS=2`

**Comment by MaxNoe** [comment]
Ok, I reproduced this with a muon run (every event should have roughly the same amount of photons).

**Comment by MaxNoe** [comment]
@thomasarmstrong 

After looking into this, I think the data is actually in the file like that, so this seems to be a bug in simtel_array itself.

I'm closing this here, but will write to Konrad.

**Comment by MaxNoe** [comment]
This looks pretty cool though:

![out](https://user-images.githubusercontent.com/5488440/82806352-e3541980-9e85-11ea-82cd-87ee299a0806.gif)

**Comment by MaxNoe** [comment]
Konrad confirmed the bug and a solution should be in the next simtel version,
fyi the fix is:

```
diff -r1.163 sim_telarray.c
2250a2251
>                   photon_count_300_550[ipix] = 0; 
```

**Comment by thomasarmstrong** [comment]
Ah ok, thanks for the information!
