### ISSUE TITLE
Attach additional event information when using `iter_mc_events`

### ISSUE THREAD

**Issue by watsonjj** [cta-observatory/pyeventio#212]
When iterating through the simtel file with `iter_mc_events`, there is currently no way to know if a particular event did create a telescope trigger in simtelarray. My feature request is to either include this information, or on a bigger scope, include all the event information that exists in the returned dict (not just the MC-related info).

**Comment by maxnoe** [comment]
This is basically a duplicate of #213

Closing in favor of this one
