### ISSUE TITLE
eventio.simtel.simtelfile issues while loading a file and parsing

### ISSUE THREAD

**Issue by davidsudm** [cta-observatory/pyeventio#218]
Hi,

I run some sim_telarray simulation, first with the sim_telarray options : 
MIN_PHOTONS = 0
MIN_PHOTOELECTRONS = 0

then convert this simtel files into npz numpy format file via importing SimTelFile from eventio.simtel.simtelfile, as:

`from eventio.simtel.simtelfile import SimTelFile`

This works fine.

then I run another simulation changing the sim_telarray options :
MIN_PHOTONS = 0
MIN_PHOTOELECTRONS = 45

or also another with :

MIN_PHOTONS = 150
MIN_PHOTOELECTRONS = 45

when I tried to use the same method described above, I got the following error :
```
/work/se1/unige/software/anaconda3/envs/lst-dev-our_MC/lib/python3.7/site-packages/corsikaio/subblocks/dtypes.py:20: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  return np.dtype(dict(**dt))
Traceback (most recent call last):
  File "/work/se1/unige/software/prog/simtel_chain/validation/convert_simtel_to_npz/read_simtel_all.py", line 116, in <module>
    entry(files, output, max_event_id)
  File "/work/se1/unige/software/prog/simtel_chain/validation/convert_simtel_to_npz/read_simtel_all.py", line 57, in entry
    with SimTelFile(file) as f:
  File "/work/se1/unige/software/anaconda3/envs/lst-dev-our_MC/lib/python3.7/site-packages/eventio/simtel/simtelfile.py", line 111, in __init__
    self.next_low_level()
  File "/work/se1/unige/software/anaconda3/envs/lst-dev-our_MC/lib/python3.7/site-packages/eventio/simtel/simtelfile.py", line 168, in next_low_level
    self.telescope_descriptions[o.telescope_id][key] = o.parse()
  File "/work/se1/unige/software/anaconda3/envs/lst-dev-our_MC/lib/python3.7/site-packages/eventio/simtel/objects.py", line 417, in parse
    HV_disabled = read_array(byte_stream, count=n_trig_disabled, dtype='i4')
  File "/work/se1/unige/software/anaconda3/envs/lst-dev-our_MC/lib/python3.7/site-packages/eventio/tools.py", line 41, in read_array
    return np.frombuffer(f.read(count * dt.itemsize), count=count, dtype=dt)
ValueError: buffer is smaller than requested size
```

it seems that the simtel files created under values different than 0 for MIN_PHOTOELECTRONS and MIN_PHOTONS **can't be opened** (or open correctly), in addition the **parsing** is also **not working**. 

By looking into the documentation I saw I could also used `EventIOFile` to open the file via :
`from eventio import EventIOFile`

when using this method the simtel files open correctly.

I am using currently running on :

Scientific Linux release 6.10 (Carbon)
eventio 1.4.1
python  3.7.6

To create the simtel files I used :
corsika7.7_simtelarray_2020-06-29
sim_telarray built with `prod5-lp-sc-baseline` option (allowing up to 14000 pixels cameras)

Thank you

**Comment by maxnoe** [comment]
EventIO files is more low-level that does not try to parse any data until you ask it to do so.

Can you provide the files somehow? E.g. via dropbox/google drive / nextcloud?

**Comment by davidsudm** [comment]
Dear Maximilian,

You can find both files in the link below :
[https://www.dropbox.com/sh/0ybe200330avkn1/AAAT-begxtENZgtudl2o6BCJa?dl=0](url)

corsika_min_ph_pe_non_zero.simtel.gz -> this is the failing-to-load file
corsika_min_ph_pe_zero.simtel.gz -> this is successful-to-load file

The both differ in the amount of events, the **non_zero** has more events than the **zero** one, therefore that difference in size

**Comment by davidsudm** [comment]
Just to add that :

`MCEvent` and `MCShower` instances can be parsed successfully

```
eventio_print_object_information /work/se3/davidsudm/lst_sipm_task/simtel/lst-sipm-pmma/output/min_photon_proton_nsbx1/corsika_run102.simtel.gz
 Type | Version | Level | #Objects | eventio-class
------------------------------------------------------------
   70 |       1 |     0 |        1 | simtel.objects.History
   71 |       1 |     1 |        1 | simtel.objects.HistoryCommandLine
   72 |       1 |     1 |      147 | simtel.objects.HistoryConfig
  100 |       2 |     0 |        1 | histograms.Histograms
 1204 |       0 |     0 |     1396 | iact.objects.TelescopeData
 1208 |       2 |     1 |     1396 | iact.objects.PhotoElectrons
 1212 |       0 |     0 |        1 | iact.objects.InputCard
 1216 |       1 |     0 |        1 | iact.objects.AtmosphericProfile
 2000 |       2 |     0 |        1 | simtel.objects.RunHeader
 2001 |       4 |     0 |        1 | simtel.objects.MCRunHeader
 2002 |       5 |     0 |        1 | simtel.objects.CameraSettings
 2003 |       1 |     0 |        1 | simtel.objects.CameraOrganization
 2004 |       3 |     0 |        1 | simtel.objects.PixelSettings
 2005 |       0 |     0 |        1 | simtel.objects.DisabledPixels
 2006 |       0 |     0 |        1 | simtel.objects.CameraSoftwareSettings
 2007 |       0 |     0 |        1 | simtel.objects.PointingCorrection
 2008 |       0 |     0 |        1 | simtel.objects.DriveSettings
 2009 |       3 |     1 |      224 | simtel.objects.TriggerInformation
 2010 |       0 |     0 |      224 | simtel.objects.ArrayEvent
 2011 |       3 |     2 |      224 | simtel.objects.TelescopeEventHeader
 2013 |       3 |     2 |      224 | simtel.objects.ADCSamples
 2014 |       5 |     2 |      195 | simtel.objects.ImageParameters
 2016 |       1 |     2 |      224 | simtel.objects.PixelTiming
 2020 |       1 |     0 |   100000 | simtel.objects.MCShower
 2021 |       1 |     0 |  1000000 | simtel.objects.MCEvent
 2022 |       0 |     0 |        1 | simtel.objects.CameraMonitoring
 2023 |       3 |     0 |        1 | simtel.objects.LaserCalibration
 2026 |       2 |     0 |      224 | simtel.objects.MCPhotoelectronSum
 2027 |       0 |     2 |      195 | simtel.objects.PixelList
 2100 |       0 |     1 |      224 | simtel.objects.TrackingPosition
 2200 |       1 |     1 |      224 | simtel.objects.TelescopeEvent
------------------------------------------------------------
```

**Comment by maxnoe** [comment]
I identified the problem, a wrong variable is used for the number of pixels at that point.

Can you produce a similar file with less events? So that the size is maybe < 5 MB?

**Comment by maxnoe** [comment]
```
    416         n_HV_disabled = read_int(byte_stream)
--> 417         HV_disabled = read_array(byte_stream, count=n_trig_disabled, dtype='i4')
```
This should be `n_HV_disabled` instead of `n_trig_disabled` in line 417. Probably a copy/paste error.

**Comment by maxnoe** [comment]
@davidsudm never mind the new file, I was able to cut the file you send appropriately to include it in the test resources.

**Comment by maxnoe** [comment]
Ah, and just as a side note, I think this has nothing to do with the min photons options.

It failed because the number of disabled trigger pixels was not the same as the number of pixels with disabled HV.

**Comment by maxnoe** [comment]
Fixed in #219, will release 1.4.2 as soon as it is merged

**Comment by mexanick** [comment]
great, thanks! We fixed in in our private installation meanwhile and will update to 1.4.2. as soon as it will be available on PyPi

**Comment by davidsudm** [comment]
Thank you, @maxnoe , it works!

**Comment by maxnoe** [comment]
release 1.4.2 is made and should be on pypi in a couple of minutes.

**Comment by davidsudm** [comment]
> Ah, and just as a side note, I think this has nothing to do with the min photons options.
> 
> It failed because the number of disabled trigger pixels was not the same as the number of pixels with disabled HV.

Something it is not clear yet for me @mahnen. How does it explain that it worked for the min_pe and min_photons equals to 0 but failed for non 0 values?
does the min_pe option actually can change the number of pixels by enabling or disabling them?

**Comment by maxnoe** [comment]
I don't know. Maybe it was just chance? How do you simulate the disabled pixels / non disabled pixels?

I am not really an expert on the inner workings of simtel, only the files that come out.

**Comment by davidsudm** [comment]
Between the 2 files I sent, the only main difference is the value of min_photoelectrons and min_photons, beside the assumed threshold that might differ. However, the rest of the configuration of the telescope is the same.

We select our trigger conditon via the analogsum parameter for trigger plus a camera_config file that has the required geometry of our telescope and the pixels it needs to sum (sectors).

We will ask to Konrad about it since he must know if the min_pe option actually disables pixels!

Thank you

**Comment by maxnoe** [comment]
Looking at `set_disabled_pixels` in `reconstruct.c`, there is an option to have random pixels broken.

Do you have `broken_pixels_fraction > 0`?

**Comment by davidsudm** [comment]
Fro what I see in sim_telarray documentationm, this parameter is passed via :

• DEAD_PIXELS
(type: Int, items: MAX_DEAD_PIXELS, default: "all: -1") List of broken pixels. Value of ’-1’ terminates the list.

in my telescope simtel config file as well as in the log outputs I got :

```
    DEAD_PIXELS       Int      20                          all: -1  
                      Current:   all: -1 
    DEAD_PIXEL_PROBability
                      Double   1        0        1         0        0 
    DEAD_BOARD_PROBability
                      Double   1        0        1         0        0 
    DEAD_MODULE_PROBability
                      Double   1        0        1         0        0 
```

So they are all set to 0 and all pixels are unbroken
