### ISSUE TITLE
Index error when parsing event trigger times from sim_telarray file

### ISSUE THREAD

**Issue by FrancescoGSaturni** [cta-observatory/pyeventio#255]
Hello,

when reading triggered events in a single-telescope sim_telarray file, I get the following error when reaching a peculiar event:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/nsb/lib/python3.10/site-packages/eventio/simtel/simtelfile.py", line 291, in iter_array_events
    self.next_low_level()
  File "/opt/anaconda3/envs/nsb/lib/python3.10/site-packages/eventio/simtel/simtelfile.py", line 163, in next_low_level
    self.current_array_event = parse_array_event(
  File "/opt/anaconda3/envs/nsb/lib/python3.10/site-packages/eventio/simtel/simtelfile.py", line 428, in parse_array_event
    telescope_events[o.telescope_id] = parse_telescope_event(o)
  File "/opt/anaconda3/envs/nsb/lib/python3.10/site-packages/eventio/simtel/simtelfile.py", line 496, in parse_telescope_event
    event['pixel_trigger_times'] = o.parse()
  File "/opt/anaconda3/envs/nsb/lib/python3.10/site-packages/eventio/simtel/objects.py", line 1770, in parse
    trigger_times['trigger_times'], length = varint_array(data, n_times, offset=length)
  File "src/eventio/var_int.pyx", line 151, in eventio.var_int.varint_array
  File "src/eventio/var_int.pyx", line 167, in eventio.var_int.varint_array
IndexError: Out of bounds on buffer access (axis 0)
```
After this error, the event-reading loop stops and there is no way to have it proceeding further by e.g. ignoring the error.

Apparently, this error is related to a wrong parsing of the extension event['telescope_events'][1]['pixel_trigger_times']['trigger_times']. In fact, while other triggered events in that file have a length of that extension < 2000 elements, the critical one has length of 2009 elements. Although this is the only difference that I could spot between events correctly parsed and the one that prompts the error, I am not sure if it is due to the fact that the extension length exceeding 2000 elements is the real cause of error.

I cannot attach the problematic file since it is too big. The code that I use for reading the events is simply:

```
import eventio
path = '[/path/to/stored/simtel/file/]'
file = '[filename.simtel.gz]'
input_url = path + file
f = eventio.SimTelFile(input_url)
for event in f:
    [do something]
```

Any hints? Many thanks in advance,
Francesco G.

**Comment by maxnoe** [comment]
Hi @FrancescoGSaturni ,

Can you provide the file? If it is large, I can offer you a cloud space to drop it.

Could you also provide the output of `eventio_print_structure` (maybe upload it as a txt file here, since it can be quite large?)

I.e. `eventio_print_structure <file> > file_structure.txt`

**Comment by FrancescoGSaturni** [comment]
Hi @maxnoe ,

here is the link to the file:

https://drive.google.com/file/d/1Mnj4o_qhDi4xm0GQ94izhiM06iYY2cdG/view?usp=share_link

Also, please find linked here the relative the file_structure.txt file (it looks like the issue is in the sim_telarray file itself):

https://drive.google.com/file/d/1BkEPEpzejM7B0tt14eji12wvOkDclyjI/view?usp=share_link

**Comment by FrancescoGSaturni** [comment]
It turned out indeed that the file being analyzed got truncated because of a hidden segfault that happened during the sim_telarray run. Since this is a very rare occurrence when running sim_telarray locally (at least in my experience) - this simulation is in fact running neither on GRID nor on telescope clusters - the error got essentially unnoticed.

I am reproducing the corrupted file from scratch, therefore the issue can be closed.

**Comment by maxnoe** [comment]
Thanks @FrancescoGSaturni
