### ISSUE TITLE
Support for new random mono trigger in sim_telarray

### ISSUE THREAD

**Issue by orelgueta** [cta-observatory/pyeventio#261]
Konrad implemented a new `RANDOM_MONO_PROBability` option to allow a certain fraction of triggered telescope events to randomly pass the stereo event selection in a way very similar to muon ring candidates do. This was a request from the NectarCam team to allow studying muons triggering single telescopes in shower events (see [this issue](https://gitlab.cta-observatory.org/cta-science/simulations/request-new-simulations/-/issues/12)).

As a result, the trigger block has changed in order to flag such random mono triggers. Reading a file which includes the random mono trigger with the current pyeventio release leads to the following error 
```
Traceback (most recent call last):
    trigger_information = o.parse()
  File "anaconda3/envs/eventio/lib/python3.9/site-packages/eventio/simtel/objects.py", line 620, in parse
    comp['alt'] = read_float(byte_stream)
  File "anaconda3/envs/eventio/lib/python3.9/site-packages/eventio/tools.py", line 28, in read_float
    return struct.unpack('<f', f.read(4))[0]
struct.error: unpack requires a buffer of 4 bytes
```

Support for the random trigger should be added to pyeventio. The exact details of the new trigger block will be provided soon. In the meantime, an example output file which was produced with a random mono trigger can be found in [this link](https://syncandshare.desy.de/index.php/s/K5kL95rDDnS5LQq).

**Comment by maxnoe** [comment]
I would expect that any changes to the binary format of eventio are signaled by a version number increase of the corresponding object and that you then get an error specifically about an unsupported object version.

Are you sure the file is OK?

**Comment by orelgueta** [comment]
It seems this change is seen only when a mono trigger is actually triggered. I simulated three different samples with the same version, one without the RANDOM_MONO_PROBability option, one with that option set to a very low probability and one with setting it to high probability so that we definitely get at least one event. Only in the latter case I got the error, when there are no mono events triggering, the file is read without issues.

I therefore conclude that some trigger bits are changed only when for those mono triggers and not for the entire sample and that the version number was not changed. I can provide example files if you think they are useful.

**Comment by maxnoe** [comment]
The Version check for the trigger is there: https://github.com/cta-observatory/pyeventio/blob/94ebedd3c38ed10810a3aa9eafd734c986fdf56e/src/eventio/simtel/objects.py#L569

**Comment by orelgueta** [comment]
Yes and from the error above it seems the version remained at 3 because otherwise we wouldn't have gotten an error about `comp['alt']` or `comp['speed_of_light']` (which I saw in a different file).

**Comment by Tobychev** [comment]
I think what Max means is that the version being the same despite there being a change in the binary format is a bug in the software generating these files.

**Comment by mdpunch** [comment]
> I think what Max means is that the version being the same despite there being a change in the binary format is a bug in the software generating these files.

A bug in `simtelarray` or further downstream, Tomas?

**Comment by orelgueta** [comment]
@maxnoe could I please ask for your help in implementing the necessary changes? 
If I understand correctly, in the following line we don't read enough bits to support this in the `teltrg_type_mask`, is that correct?

https://github.com/cta-observatory/pyeventio/blob/94ebedd3c38ed10810a3aa9eafd734c986fdf56e/src/eventio/simtel/objects.py#L600

What makes me doubt it is that even if bits 4-31 are zero, they still would have been read by the next line reading the stream. But as far as I know, we don't see such an error in the trigger times read out.

**Comment by maxnoe** [comment]
@kbernloehr it seems there is different logical needed to read the object in case of a mono trigger, so it can't just be "ignored". Otherwise the Reader wouldn't have thrown an error.

I'll have a look later, currently not near a computer.

**Comment by maxnoe** [comment]
This line could be the culprit if a new trigger bit latter was added: https://github.com/cta-observatory/pyeventio/blob/94ebedd3c38ed10810a3aa9eafd734c986fdf56e/src/eventio/simtel/objects.py#L609

**Comment by maxnoe** [comment]
The correct solution is probably to use a function that counts the number of  1 bits and checks if it's 1.

https://docs.python.org/3.10/library/stdtypes.html#int.bit_count

**Comment by orelgueta** [comment]
Yes this line will not pick up the new random trigger and therefore will not read the trigger time from the stream. However, in these lines

https://github.com/cta-observatory/pyeventio/blob/94ebedd3c38ed10810a3aa9eafd734c986fdf56e/src/eventio/simtel/objects.py#L600-L602

We read only an 8 bits int while Konrad describes a 32 bit mask and the random trigger is at the 10th bit which we wouldn't read with `uint8` if I understand correctly.
I will wait for you to be in front of a computer anyway. It's not urgent.

**Comment by kbernloehr** [comment]
No, that would not be correct. We had simulations in the past where a telescope could have multiple trigger types, for example to compare the thresholds achieved with majority versus analog sum etc.
The digital majority is already documented but not implemented (that would be mask = 0b1000, if it is the only trigger type in the telescope). The only bits required to be zero are, currently, 4-7 and 16-31.  All other bits can come in any combination.

**Comment by maxnoe** [comment]
Fixed in #261

**Comment by maxnoe** [comment]
> We read only an 8 bits int while Konrad describes a 32 bit mask and the random trigger is at the 10th bit which we wouldn't read with uint8 if I understand correctly.

Yes, this is true, but not the reason why it failed. Even with the mono trigger, the trigger masked was still below 128, so the variable int array used to store the 32-bit value was actually stored using one byte.

However, the check below for the storing of individual trigger times per trigger type didn't work, as two bits were now set.

I fixed both, we now correctly read the variable length integer and only look at the first 4 bits for the individual trigger times.

**Comment by kosack** [comment]
> Fixed in https://github.com/cta-observatory/pyeventio/issues/261

I think you mean #262

**Comment by mdpunch** [comment]
Thanks for all your efforts on this (it's my fault it's being tested now!)...

Question maybe to Kark @kosack:  At what point do the different bits for the event classification in `simtelarray` get translated into the "A.4.3 Event type Definition." of the R1 Data Model?

As discussed elsewhere, these random mono triggers could be either `trigger type == 2` (ACADA requested this event be captured) or probably better to use one of the unused `trigger_type`s >3, for "special MC simulation events" or something (which would have the advantage that the subtypes, or `event_type`s can then be used to "encode" some of the other bits.

Maybe this isn't the best forum to discuss this, but I don't know where is?

**Comment by maxnoe** [comment]
This is done in the `ctapipe.io.SimTelEventSource` here:

https://github.com/cta-observatory/ctapipe/blob/73a154591f4935084aa44887d8a86f735de9a3d5/ctapipe/io/simteleventsource.py#L923

But it seems we just always fill SUBARRAY for data events, and are not yet looking at these trigger bits.

So that's something to be added.
